Data_Science_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from Data_Science_Web_App import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500, handler403, handler400

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_view, name='index_view'),
    path('Data_Science_Web_App/', include('Data_Science_Web_App.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# Only for DEBUG = True
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 = 'Data_Science_Web_App.views.error_404'
handler500 = 'Data_Science_Web_App.views.error_500'
handler403 = 'Data_Science_Web_App.views.error_403'
handler400 = 'Data_Science_Web_App.views.error_400'

Data_Science_Web_App/urls.py
from django.urls import path
from . import views

app_name = 'Data_Science_Web_App'
urlpatterns = [
    path('data_upload/', views.package, name='data_upload'),
    path('algorithms/', views.AlgorithmView.as_view(), name='AlgorithmView'),
    path('visualizations/', views.VisualView.as_view(), name='VisualView'),
    path('about_us/', views.AboutView.as_view(), name='AboutView'),
    path('variable_stats/', views.variable_statistics, name='variable_statistics'),
    path('plot/', views.plot, name='plot'),
    path('histogram/', views.histoplot, name='histoplot'),
    path('density_function/', views.density, name='density'),
    path('gaussian_smoothing/', views.gaussian, name='gaussian'),
    path('interpolation_NAN/', views.interpolation, name='interpolation'),
    path('transformation/', views.transformation, name='transformation'),
    path('visual/', views.visual, name = 'visual'),
    path('curve_fitter/', views.curve_fitter, name='curve_fitter'),
    path('log/', views.log, name='log'),
    path('custom/', views.custom, name='custom'),
    path('custom_visualization/', views.custom_visualization, name='custom_visualization'),
]

Data_Science_Web_App/forms.py
from django import forms
# from django.core import validators

class PlotChartForm(forms.Form):
    key = forms.CharField(required=False, label = 'Key')
    data_file = forms.FileField(required=False, label = 'CSV File')
    xIndex = forms.IntegerField(label = 'Index of X axis')
    yIndex = forms.IntegerField(label = 'Index of Y axis')
    xLabel = forms.CharField(required=False, label = 'Label for X axis')
    yLabel = forms.CharField(required=False, label = 'Label for Y axis')
    title = forms.CharField(required=False, label = 'Title of the graph')
    lowerX = forms.DecimalField(required=False, label = 'Minimum value of X axis')
    upperX = forms.DecimalField(required=False, label = 'Maximum value of X axis')
    lowerY = forms.DecimalField(required=False, label = 'Minimum value of Y axis')
    upperY = forms.DecimalField(required=False, label = 'Maximum value of Y axis')
    alphaVal = forms.DecimalField(required=False, label = 'Alpha Value')


class HistoForm(forms.Form):
    key = forms.CharField(required=False, label = 'Key')
    data_file = forms.FileField(required=False, label = 'CSV File')
    colN = forms.IntegerField(label = 'Column Number')
    xLabel = forms.CharField(required=False, label = 'Label for X axis')
    yLabel = forms.CharField(required=False, label = 'Label for Y axis')
    title = forms.CharField(required=False, label = 'Title of the graph')
    lowerX = forms.DecimalField(required=False, label = 'Minimum value of X axis')
    upperX = forms.DecimalField(required=False, label = 'Maximum value of X axis')
    lowerY = forms.DecimalField(required=False, label = 'Minimum value of Y axis')
    upperY = forms.DecimalField(required=False, label = 'Maximum value of Y axis')
    hStyle = forms.ChoiceField(widget=forms.RadioSelect, choices = [('bar', 'Bar'),('barstacked','Bar Stacked'), ('step', 'Step'), ('stepfilled', 'Step Filled')], label = 'Which histogram style would you like?')
    binS = forms.IntegerField(required=False, label = 'Size of bins')
    densYes = forms.ChoiceField(widget=forms.RadioSelect, choices=[(True, 'Yes'), (False, 'No')], label = 'Do you want a density function?')


class InterpolationForm(forms.Form):
    key = forms.CharField(required=False, label = 'Key')
    data_file = forms.FileField(required=False, label = 'CSV File')
    xIndex = forms.IntegerField(label = 'Index of X axis')
    yIndex = forms.IntegerField(label = 'Index of Y axis')
    xLabel = forms.CharField(required=False, label = 'Label for X axis')
    yLabel = forms.CharField(required=False, label = 'Label for Y axis')
    title = forms.CharField(required=False, label = 'Title of the graph')
    lowerX = forms.DecimalField(required=False, label = 'Minimum value of X axis')
    upperX = forms.DecimalField(required=False, label = 'Maximum value of X axis')
    lowerY = forms.DecimalField(required=False, label = 'Minimum value of Y axis')
    upperY = forms.DecimalField(required=False, label = 'Maximum value of Y axis')
    iKind = forms.CharField(required=False, label = 'Kind of Interpolation')

class CurveFitterForm(forms.Form):
    key = forms.CharField(required=False, label = 'Key')
    data_file = forms.FileField(required=False, label = 'CSV File')
    xIndex = forms.IntegerField(label = 'Index of X axis')
    yIndex = forms.IntegerField(label = 'Index of Y axis')
    xLabel = forms.CharField(required=False, label = 'Label for X axis')
    yLabel = forms.CharField(required=False, label = 'Label for Y axis')
    title = forms.CharField(required=False, label = 'Title of the graph')
    lowerX = forms.DecimalField(required=False, label = 'Minimum value of X axis')
    upperX = forms.DecimalField(required=False, label = 'Maximum value of X axis')
    lowerY = forms.DecimalField(required=False, label = 'Minimum value of Y axis')
    upperY = forms.DecimalField(required=False, label = 'Maximum value of Y axis')
    fit_func = forms.CharField(required=False, label = 'Fit Function')
    y_func = forms.CharField(required=False, label = 'Y Function')

class LogForm(forms.Form):
    key = forms.CharField(required=False, label = 'Key')
    data_file = forms.FileField(required=False, label = 'CSV File')
    colN = forms.IntegerField(label = 'Column Number')
    negative = forms.ChoiceField(widget=forms.RadioSelect, choices=[(True, 'Yes'), (False, 'No')], label = 'Do you want your values to be non negative?')
    package = forms.ChoiceField(widget=forms.RadioSelect, choices=[(True, 'Package'), (False, 'Download')], label = 'Do you want to package or download your data?')

class CustomForm(forms.Form):
    key = forms.CharField(required=False, label = 'Key')
    data_file = forms.FileField(required=False, label = 'CSV File')
    code = forms.CharField(widget=forms.Textarea(attrs={'rows':10, 'cols':100, 'style': 'width:100%;'}), label = 'Code')
    package = forms.ChoiceField(widget=forms.RadioSelect, choices=[(True, 'Package'), (False, 'Download')], label = 'Do you want to package or download your data?')

class VarForm(forms.Form):
    key = forms.CharField(required=False, label = 'Key')
    data_file = forms.FileField(required=False, label = 'CSV File')
    rc = forms.ChoiceField(widget=forms.RadioSelect, choices=[(True, 'Row'), (False, 'Column')], label = 'Row or Column?')
    num = forms.IntegerField(label = 'Row/Column Number')

class CustomVisualForm(forms.Form):
    key = forms.CharField(required=False, label = 'Key')
    data_file = forms.FileField(required=False, label = 'CSV File')
    code = forms.CharField(widget=forms.Textarea(attrs={'rows':10, 'cols':100, 'style': 'width:100%;'}), label = 'Code')

class UploadForm(forms.Form):
    data_file = forms.FileField(required=False, label = 'CSV File')

Data_Science_Web_App/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.core.files.storage import default_storage
from Data_Science_Web_App.algorithms.variable_stats import variable_stats, strWSpace
from Data_Science_Web_App.algorithms.xyplot import xyplot
from Data_Science_Web_App.algorithms.histo import histo
from Data_Science_Web_App.algorithms.interp import interp
from Data_Science_Web_App.algorithms.curveFitter import curveFitter
from Data_Science_Web_App.algorithms.log import logarithm
from Data_Science_Web_App.algorithms.key import generate_key
from Data_Science_Web_App.algorithms.locator import locate
from django.http import HttpResponse
import pytz
import datetime
from . import forms
from IPython.display import HTML
from Data_Science_Web_App.models import TemporaryFile
import os
import pandas as pd
import mpld3
import csv
import random
import string
import simplejson
from Data_Science_Project.settings import MEDIA_ROOT, BASE_DIR

graph_path = os.path.abspath('media/graphs')



class AboutView(TemplateView):
    template_name = 'Data_Science_Web_App/about.html'



class AlgorithmView(TemplateView):
    template_name = 'Data_Science_Web_App/algorithms.html'



class VisualView(TemplateView):
    template_name = 'Data_Science_Web_App/visualization.html'



def index_view(request):

    template_name = 'Data_Science_Web_App/index.html'

    if request.method == "GET":

        utc = pytz.UTC
        objects = TemporaryFile.objects.all()

        for object in objects.iterator():

            if object.time_created < utc.localize(datetime.datetime.now())-datetime.timedelta(minutes=1):

                self_file = TemporaryFile.objects.get(pk = object.pk)
                data = str(object.data)
                os.remove(os.path.join(MEDIA_ROOT, data))
                self_file.delete()

    return render(request, template_name)





def variable_statistics(request):

    template_name = 'Data_Science_Web_App/variable_stats.html'
    form = forms.VarForm()

    if request.method == "GET":

        context={
            'success': False,
            'form': form,
            'message': "",
        }
        return render(request, template_name, context)

    if request.method == "POST":

        form = forms.VarForm(request.POST, request.FILES)

        if form.is_valid():

            key = form.cleaned_data['key']
            data_file = form.cleaned_data['data_file']
            rc = form.cleaned_data['rc']
            num = form.cleaned_data['num']

            if key != "":

                try:

                    csv_file = locate(key)
                    data_set = pd.read_csv(csv_file)

                except:

                    context = {
                        'success': False,
                        'form': form,
                        'message': 'The key was invalid',
                    }
                    return render(request, template_name, context)

                if rc=="True":

                    try:

                        data_set = data_set.iloc[num].to_list()

                    except:

                        context = {
                            'success': False,
                            'form': form,
                            'message': 'Please ensure that the data is formatted properly',
                        }
                        return render(request, template_name, context)

                else:

                    try:

                        data_set = data_set.iloc[:,num].to_list()

                    except:

                        context = {
                            'success': False,
                            'form': form,
                            'message': 'Please ensure that the data is formatted properly',
                        }
                        return render(request, template_name, context)

            elif data_file != None:

                if not data_file.name.endswith('.csv'):

                    context={
                        'success': False,
                        'form': form,
                        'error_message': 'Please ensure that the uploaded file is a CSV file',
                    }
                    return render(request, template_name, context)

                data_set = pd.read_csv(data_file)

                if rc=="True":

                    try:

                        data_set = data_set.iloc[num].tolist()

                    except:

                        context = {
                            'success': False,
                            'form': form,
                            'message': 'Please ensure that the data is formatted properly',
                        }
                        return render(request, template_name, context)

                else:

                    try:

                        data_set = data_set.iloc[:, num].tolist()

                    except:

                        context = {
                            'success': False,
                            'form': form,
                            'message': 'Please ensure that the data is formatted properly',
                        }
                        return render(request, template_name, context)

        else:

            context = {
                'success': False,
                'form': form,
                'error_message': 'Please fill out the required fields',
            }
            return render(request, template_name, context)

        try:

            avgNum, mode_return, left, mid, right, std, std1lower, std1upper, std2lower, std2upper, std3lower, std3upper, variance, Q1, Q3, IQR, range =  variable_stats(data_set)

            if mode_return == None:

                modeNum = "No Mode"

            else:

                modeNum = " ".join(list(map(strWSpace, mode_return)))[:-2]

        except:

            context={
                'success': False,
                'form': form,
                'message': 'Please ensure that the data is formatted properly',
            }
            return render(request, template_name, context)

        context = {
            'success': True,
            'form': form,
            'num': avgNum,
            'left': left,
            'mid': mid,
            'right': right,
            'mode': modeNum,
            'std': std,
            'std1lower': std1lower,
            'std1upper': std1upper,
            'std2lower': std2lower,
            'std2upper': std2upper,
            'std3lower': std3lower,
            'std3upper': std3upper,
            'variance': variance,
            'Q1': Q1,
            'Q3': Q3,
            'IQR': IQR,
            'range': range
        }

        return render(request, template_name, context)





def plot(request):

    template_name = 'Data_Science_Web_App/plot.html'
    form = forms.PlotChartForm()
    context={
        'success': False,
        'form': form,
        'error_message': 'Please fill out the required fields!'
    }

    if request.method == 'POST':

        form = forms.PlotChartForm(request.POST, request.FILES)

        if form.is_valid():

            data_file = form.cleaned_data['data_file']
            key = form.cleaned_data['key']
            xIndex = form.cleaned_data['xIndex']
            yIndex = form.cleaned_data['yIndex']
            xLabel = form.cleaned_data['xLabel']
            yLabel = form.cleaned_data['yLabel']
            title = form.cleaned_data['title']
            lowerX = form.cleaned_data['lowerX']
            upperX = form.cleaned_data['upperX']
            lowerY = form.cleaned_data['lowerY']
            upperY = form.cleaned_data['upperY']
            alphaVal = form.cleaned_data['alphaVal']

            if data_file != None:

                if not data_file.name.endswith('.csv'):

                    context={
                        'success': False,
                        'form': form,
                        'error_message': 'Please ensure that the uploaded file is a CSV file'
                    }
                    return render(request, template_name, context)

                data_set = pd.read_csv(data_file)

            elif key != None:

                try:

                    csv_file = locate(key)
                    data_set = pd.read_csv(csv_file)

                except:

                    context = {
                        'success': False,
                        'form': form,
                        'error_message': 'The key was invalid'
                    }
                    return render(request, template_name, context)

            else:

                context = {
                    'success': False,
                    'form': form,
                    'error_message': 'Please provide a CSV File or Key'
                }
                return render(request, template_name, context)

            xR = [lowerX, upperX]
            yR = [lowerY, upperY]

            try:

                figure = xyplot(data_set, xIndex, yIndex, xLabel, yLabel, title, xR, yR, alphaVal)
                graph_image = 'graph.png'
                figure.savefig(os.path.join(graph_path, graph_image))

            except:

                context={
                    'success': False,
                    'form': form,
                    'error_message': 'Something went wrong, please ensure that the CSV file is properly formatted'
                }
                return render(request, template_name, context)

            context = {
                'success': True,
                'form': form,
                'error_message': 'The graph should have been generated, but something went wrong'
            }

    return render(request, template_name, context)





def visual(request):

    template_name = 'Data_Science_Web_App/visual.html'

    if request.method == "GET":

        context={
            'loaded_data': 'Please input a key',
        }
        return render(request, template_name, context)

    try:

Data_Science_Web_App/templates/Data_Science_Web_App/about.html
{% extends 'Data_Science_Web_App/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>We are just some highschoolers that like STEM!</h1>
  </div>
</div>

{% endblock %}

Data_Science_Web_App/templates/Data_Science_Web_App/algorithms.html
{% extends 'Data_Science_Web_App/base.html' %}
{% load static %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1 style = "display:inline-block;">Algorithms</h1>
    <form style = "display:inline-block;float:right;" action="{% url 'Data_Science_Web_App:custom' %}" method="GET">
      {% csrf_token %}
      <input type="submit" value="Custom Algorithm">
    </form>
    <div id = "myDropdown" class="dropdown-content">
      <input type="text" placeholder="Search Algorithms..." id="myInput" onkeyup="filterFunction()">

      <button class="accordion">
        <p style = "display:inline-block;">Variable Statistics</p>
        <form style = "display:inline-block;float:right;" action="{% url 'Data_Science_Web_App:variable_statistics' %}" method="GET">
          {% csrf_token %}
          <input type="submit" value="Select">
        </form>
      </button>
      <div class="panel">
        <br>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#VariableStatsModal">
          Description
        </button>

        <!-- Modal -->
        <div class="modal fade" id="VariableStatsModal" tabindex="-1" role="dialog" aria-labelledby="VariableStatsModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="VariableStatsModalLongTitle">Variable Statistics</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p><b>Description:</b> Outputs simple variable statistics for one variable. (Mean, median, mode, range, standard deviation)</p>
                <p><b>Necessary Conditions:</b> 1 variable data</p>
                <p><b>Read More:</b>https://en.wikipedia.org/wiki/Mean, https://en.wikipedia.org/wiki/Median, etc (we will actually add all of them but I’m too lazy to for this mockup.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <br>
        <br>
      </div>

      <button class="accordion">
        <p style = "display:inline-block;">Logarithm</p>
        <form style = "display:inline-block;float:right;" action="{% url 'Data_Science_Web_App:log' %}" method="GET">
          {% csrf_token %}
          <input type="submit" value="Select">
        </form>
      </button>
      <div class="panel">
        <br>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#LogModal">
          Description
        </button>

        <!-- Modal -->
        <div class="modal fade" id="LogModal" tabindex="-1" role="dialog" aria-labelledby="LogModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="LogModalLongTitle">Variable Statistics</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p><b>Description:</b> Outputs simple variable statistics for one variable. (Mean, median, mode, range, standard deviation)</p>
                <p><b>Necessary Conditions:</b> 1 variable data</p>
                <p><b>Read More:</b>https://en.wikipedia.org/wiki/Mean, https://en.wikipedia.org/wiki/Median, etc (we will actually add all of them but I’m too lazy to for this mockup.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <button class="accordion">
        <p style = "display:inline-block;">Gaussian Smoothing</p>
        <form style = "display:inline-block;float:right;" action="{% url 'Data_Science_Web_App:gaussian' %}" method="GET">
          {% csrf_token %}
          <input type="submit" value="Select">
        </form>
      </button>
      <div class="panel">
        <br>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#GaussianModal">
          Description
        </button>

        <!-- Modal -->
        <div class="modal fade" id="GaussianModal" tabindex="-1" role="dialog" aria-labelledby="GaussianModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="GaussianModalLongTitle">Variable Statistics</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p><b>Description:</b> Outputs simple variable statistics for one variable. (Mean, median, mode, range, standard deviation)</p>
                <p><b>Necessary Conditions:</b> 1 variable data</p>
                <p><b>Read More:</b>https://en.wikipedia.org/wiki/Mean, https://en.wikipedia.org/wiki/Median, etc (we will actually add all of them but I’m too lazy to for this mockup.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <br>
        <br>
      </div>

      <button class="accordion">
        <p style = "display:inline-block;">Density Function</p>
        <form style = "display:inline-block;float:right;" action="{% url 'Data_Science_Web_App:density' %}" method="GET">
          {% csrf_token %}
          <input type="submit" value="Select">
        </form>
      </button>
      <div class="panel">
        <br>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#DensityModal">
          Description
        </button>

        <!-- Modal -->
        <div class="modal fade" id="DensityModal" tabindex="-1" role="dialog" aria-labelledby="DensityModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="DensityModalLongTitle">Variable Statistics</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p><b>Description:</b> Outputs simple variable statistics for one variable. (Mean, median, mode, range, standard deviation)</p>
                <p><b>Necessary Conditions:</b> 1 variable data</p>
                <p><b>Read More:</b>https://en.wikipedia.org/wiki/Mean, https://en.wikipedia.org/wiki/Median, etc (we will actually add all of them but I’m too lazy to for this mockup.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <br>
        <br>
      </div>

      <button class="accordion">
        <p style = "display:inline-block;">Data Transformation</p>
        <form style = "display:inline-block;float:right;" action="{% url 'Data_Science_Web_App:transformation' %}" method="GET">
          {% csrf_token %}
          <input type="submit" value="Select">
        </form>
      </button>
      <div class="panel">
        <br>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#DataTransformModal">
          Description
        </button>

        <!-- Modal -->
        <div class="modal fade" id="DataTransformModal" tabindex="-1" role="dialog" aria-labelledby="DataTransformModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="DataTransformModalLongTitle">Variable Statistics</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p><b>Description:</b> Outputs simple variable statistics for one variable. (Mean, median, mode, range, standard deviation)</p>
                <p><b>Necessary Conditions:</b> 1 variable data</p>
                <p><b>Read More:</b>https://en.wikipedia.org/wiki/Mean, https://en.wikipedia.org/wiki/Median, etc (we will actually add all of them but I’m too lazy to for this mockup.</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        <br>
        <br>
      </div>

    </div>
  </div>
</div>
<script src="{% static 'js/main_page.js' %}" type="text/javascript"></script>
{% endblock %}

Data_Science_Web_App/templates/Data_Science_Web_App/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Cactus</title>

    <!-- jquery -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Popper for Tooltip -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

    <!-- Custom CSS Files -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/main_page.css' %}">

    <!-- Custom JS Files -->
    <script src="{% static 'js/base.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/tooltip.js' %}" type="text/javascript"></script>

  </head>
  <body>
    <nav class="navbar navbar-expand-sm   navbar-light bg-light">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#baseNavBar" aria-controls="baseNavBar" aria-expanded="false" aria-label="Navigate">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="baseNavBar">

          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

            <li class="nav-item">
              <a class="nav-link" href="{% url 'index_view' %}">Home <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'Data_Science_Web_App:data_upload' %}">Data Upload</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'Data_Science_Web_App:AlgorithmView' %}">Algorithms</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'Data_Science_Web_App:VisualView' %}">Visualizations</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'Data_Science_Web_App:AboutView' %}">About Us</a>
            </li>

            <div id="myDropdownNav" class="dropdown-content topcorner">
              <input type="text" placeholder="Search Functionalities..." id="myInputNav" onkeyup="filterFunctionNav()">
              <a href="{% url 'Data_Science_Web_App:variable_statistics' %}">Variable Statistics</a>
              <a href="{% url 'Data_Science_Web_App:log' %}">Logarithm</a>
              <a href="{% url 'Data_Science_Web_App:gaussian' %}">Gaussian Smoothing</a>
              <a href="{% url 'Data_Science_Web_App:density' %}">Density Function</a>
              <a href="{% url 'Data_Science_Web_App:transformation' %}">Data Transformation</a>
              <a href="{% url 'Data_Science_Web_App:custom' %}">Custom Algorithm</a>
              <a href="{% url 'Data_Science_Web_App:plot' %}">Scatter Plot</a>
              <a href="{% url 'Data_Science_Web_App:histoplot' %}">Histogram</a>
              <a href="{% url 'Data_Science_Web_App:visual' %}">Visualization</a>
              <a href="{% url 'Data_Science_Web_App:interpolation' %}">Interpolation</a>
              <a href="{% url 'Data_Science_Web_App:curve_fitter' %}">Curve Fitter</a>
            </div>

          </ul>
        </div>
      </nav>
      {% block body_block %}
      {% endblock %}
  </body>
</html>

Data_Science_Web_App/templates/Data_Science_Web_App/density.html
{% extends 'Data_Science_Web_App/base.html' %}
{% block body_block %}
<h1>This is the density function page!</h1>
{% endblock %}